microlly/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('microlly_app.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('login/', core_views.login, name='login'),
    # path('signup/', views.signup, name='signup'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microlly_app/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from microlly_app import views
from django.views.generic.base import TemplateView # new
app_name = 'microlly_app'


urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('login/', views.v_login, name='login'),
    path('logout/', views.v_logout, name='logout'),
    path('signup/', views.v_signup, name='signup'),
    path('create/', views.p_create, name='create'),
    path('bloger/<str:author>', views.p_user_list, name='p_user_list'),
    path('publi/<slug:slug>/<int:pk>', views.p_details, name='details'),
    path('details/<slug:slug>/<int:pk>', views.p_details, name='details'),
    path('edit/<slug:slug>/<int:pk>', views.p_edit, name='edit'),
    path('delete/<slug:slug>/<int:pk>', views.p_delete, name='delete'),

]

microlly_app/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

class Publication(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    body = models.TextField(max_length=450)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)
    def  __str__(self):
        return self.title
    def preview(self):
        return self.body[:50]+'...'
    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Publication.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
    def save(self, *args, **kwargs):
        self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)



    class Meta:
        ordering = ['update_date', 'creation_date','title', ]
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'

microlly_app/forms.py
from django import forms
from microlly_app import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PubliCreate(forms.ModelForm):
    class Meta:
        model = models.Publication
        fields = ['title', 'body']


class PubliEdit(forms.ModelForm):
    class Meta:
        model = models.Publication
        fields = ['title', 'body']


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2',)

microlly_app/views.py
from microlly_app.models import Publication
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.shortcuts import render, redirect , get_object_or_404
from microlly_app import forms
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
# Create your views here.

# def index(request):
#     publis = Publication.objects.all()
#     return render(request, '_base.html', {'latests_publis': publis})

def publi(request, slug):
    publi = get_object_or_404(Publication, slug=slug)
    return render(request, 'publi/details.html', {'publi': publi})

def v_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('microlly_app:index')
    else:
        form = AuthenticationForm()
    return render(request, 'users_pages/login.html', {'form': form})


def v_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('microlly_app:index')
    else:
        return redirect('microlly_app:index')


def v_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('microlly_app:index')
    else:
        form = UserCreationForm()
    return render(request, 'users_pages/signup.html', {'form': form})

def index(request):
    publis_list = Publication.objects.all().order_by('-creation_date')
    paginator = Paginator(publis_list, 9)
    page = request.GET.get('page')
    publis = paginator.get_page(page)
    return render(request, '_base.html', {'latest_publis': publis})


def p_details(request, slug, pk):
    publi = get_object_or_404(Publication, slug=slug, pk=pk)
    return render(request, 'publi/details.html', {'publi': publi})


@login_required(login_url="users_pages/login/")
def p_create(request):
    if request.method == 'POST':
        form = forms.PubliCreate(request.POST)
        if form.is_valid():
            publi = form.save(commit=False)
            publi.author = request.user
            publi.save()
            return redirect('microlly_app:index')
    else:
        form = forms.PubliCreate()
    return render(request, 'publi/p_create.html', {'form': form})


@login_required(login_url="users_pages/login/")
def p_edit(request, slug, pk):
    publi = get_object_or_404(Publication, slug=slug, pk=pk)
    form = forms.PubliEdit(request.POST or None, instance=publi)
    if request.user != publi.author:
        return redirect('microlly_app:index')
    if request.method == 'POST':
        if form.is_valid():
            publi.save()
            return redirect('microlly_app:index')
    context = {
        "form": form,
        "publi": publi,
    }
    return render(request, 'publi/p_edit.html', context)


@login_required(login_url="users_pages/login/")
def p_user_list(request, author):
    author = get_object_or_404(User, username=author)
    publis_list = Publication.objects.filter(author=author).order_by('-creation_date')
    paginator = Paginator(publis_list, 9)
    page = request.GET.get('page')
    publis = paginator.get_page(page)

    context = {
        "author": author,
        "p_user_list": publis,
    }

    return render(request, 'publi/p_user_list.html', context)

@login_required(login_url="users_pages/login/")
def p_delete(request, slug, pk):
    publi = get_object_or_404(Publication, pk=pk)
    if request.user != publi.author:
        return redirect('microlly_app:index')
    if request.method == 'POST':
        publi.delete()
        return redirect('microlly_app:index')

microlly_app/templates/_base.html
<!-- <!DOCTYPE html> -->
{% extends 'base_layout.html' %}
  
                 

                    {% block content %}
                        {% if user.is_authenticated %}
                            Hi {{ user.username }}!
                            <li role="presentation">
                                <form class="form-inline" action="{% url 'microlly_app:logout' %}" method="POST">
                                    {% csrf_token %}
                                    <button  type="submit">LOG OUT</button>
                                </form>
                            </li>
                        {% else %}
                            <p>You are not logged in</p>
                                <li role="presentation">
                                    <form class="form-inline" action="{% url 'microlly_app:login' %}" method="POST">
                                        {% csrf_token %}
                                        <button  type="submit">LOG IN</button>
                                    </form>
                                </li>
                                <li role="presentation">
                                    <form class="form-inline" action="{% url 'microlly_app:signup' %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit">SIGN UP</button>
                                    </form>
                                </li>
                        {% endif %}
                    

            <!-- manque un div-->
            {% if latest_publis %}
                <article class="row">
                    {% for publi in latest_publis %}
                        <div >
                            <div>
                                <div >
                                    <h4>
                                        <a  href="{% url 'microlly_app:details' publi.slug publi.pk %}">
                                            {{ publi.title }}</a>
                                    </h4>
                                    <p>
                                        {{publi.preview}}
                                    </p>
                                </div>
                                <div>
                                    <p>
                                        <small>
                                            Posted by: <a href="{% url 'microlly_app:p_user_list' publi.author %}">{{publi.author}}</a>
                                            <span></span>
                                            on {{publi.creation_date}}
                                        </small>
                                    </p>
                                    <p>
                                        <small>
                                            Last update: {{publi.update_date}}
                                        </small>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </article>

                <nav>
                    <ul>
                        {% if latest_publis.has_previous %}
                        <li> <a href="?page=1">&laquo; first</a> </li>
                        <li ><a  href="?page={{ latest_publis.previous_page_number }}">previous</a></li>
                        {% endif %}
                        {% if latest_publis.has_next %}
                        <li><a href="?page={{ latest_publis.next_page_number }}">next</a></li>
                        <li><a href="?page={{ latest_publis.paginator.num_pages }}">last &raquo;</a></li>
                        {% endif %}
                    </ul>
                </nav>

            {% else %}
                <p>Aucunes publications.</p>
            {% endif %}

            {% endblock %}
<!--             
            <footer>
                <p>&copy; {% now 'Y' %} LIN et MERLIER</p>
                </footer>
        </div>
      
    </body>

</html> -->

microlly_app/templates/publi/details.html
{% extends '_base.html' %}

{% block section-title %}
Details
{% endblock %}

{% block content %}
<div class="card-container">
    <div class="card border border-lightgreen mb-3">
        <div class="card-body">
            <h4 class="card-title">
                <a class="badge badge-lightgreen" href="{% url 'microlly_app:details' publi.slug publi.pk %}">
                    {{ publi.title }}</a>
            </h4>
            <p class="card-text">
                {{ publi.body }}
            </p>
        </div>
        <div class="card-footer">
            <p class="card-text">
                <small class="text-muted">
                    Posted by: 
                    {% if user.is_authenticated%}
                    <a href="{% url 'microlly_app:p_user_list' publi.author %}">{{ publi.author }}</a>
                    {% else %}
                        {{ publi.author }}
                    {% endif %}
                    <span class="text-dark"></span>
                    on {{ publi.creation_date }}
                </small>
            </p>
            <p class="card-text">
                <small class="text-muted">
                    Last update: {{ publi.update_date }}
                </small>
            </p>
        </div>
    </div>
</div>



{% if user.is_authenticated and user == publi.author %}
<div class="container d-flex flex-column justify-content-center">
    <form class="my-1" action="{% url 'microlly_app:delete' publi.slug publi.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" >Delete</button>
    </form>
    <form class="my-1" action="{% url 'microlly_app:edit' publi.slug publi.pk %}">
        {% csrf_token %}
        <button type="submit" >Edit</button>
    </form>
</div>
{% endif %}

{% endblock %}

microlly_app/templates/publi/p_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <form action="{% url 'microlly_app:create' %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit"  value="Create">
    </form>
{% endblock %}

microlly_app/templates/publi/p_edit.html
{% extends 'base_layout.html' %}
{% block content %}
    <form $action="{% url 'microlly_app:edit' publi.slug publi.pk %}" method="POST">
        {% csrf_token %}
        {% include 'form.html' with form=form %}
        <input type="submit"  value="Edit">
    </form>
    <form action="{% url 'microlly_app:delete' publi.slug publi.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" >Delete</button>
    </form>
{% endblock %}

microlly_app/templates/publi/p_user_list.html
{% extends 'base_layout.html' %}

{% block content %}
<article class="row">
    {% for publi in p_user_list %}
    <div>
        <div>
            <div>
                <h4>
                    <a href="{% url 'microlly_app:details' publi.slug publi.pk %}">
                        {{ publi.title }}</a>
                </h4>
                <p>
                    {{publi.preview}}
                </p>
            </div>
            <div>
                <p>
                    <small>
                        Posted by: <a href="{% url 'microlly_app:p_user_list' publi.author %}">{{publi.author}}</a>
                        <span></span>
                        on {{publi.creation_date}}
                    </small>
                </p>
                <p>
                    <small>
                        Last update: {{publi.update_date}}
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</article>

<nav>
    <ul>
        {% if p_user_list.has_previous %}
        <li> <a  href="?page=1">&laquo; first</a> </li>
        <li><a href="?page={{ p_user_list.previous_page_number }}">previous</a></li>
        {% endif %}
        {% if p_user_list.has_next %}
        <li><a href="?page={{ p_user_list.next_page_number }}">next</a></li>
        <li ><a href="?page={{ p_user_list.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

microlly_app/templates/users_pages/login.html
<!-- templates/users_pages/login.html -->
<!-- <h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> -->

{% block section-title %}
Login
{% endblock %}

{% block content %}
<form class="d-flex flex-column" action="{% url 'microlly_app:login' %}" method="POST">
    {% csrf_token %}
    {% include 'form.html' with form=form %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" class="btn btn-dark" value="Login">
</form>
{% endblock %}

microlly_app/templates/users_pages/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/normalize.css' %}" />
    <title>Microlly</title>
</head>


<body>
    <header class="banner">
        <nav >
            <div>
                <ul >
                        <li role="presentation">
                        <form class="form-inline" action="{% url 'microlly_app:index' %}" method="POST">
                            {% csrf_token %}
                            <button  type="submit">HOME</button>
                        </form>
                    </li>
                    {% if user.is_authenticated %}
                    <li role="presentation">
                        <form class="form-inline" action="{% url 'microlly_app:create' %}" method="POST">
                            {% csrf_token %}
                            <button  type="submit">CREATE</button>
                        </form>
                    </li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li class="nav-item mx-1">
                        <a  href="/admin">ADMIN</a>
                    </li>
                    {% endif%}
                </ul>
            </div>
        </nav>
        <div >
                <h3 class="text-muted">🎲 Microlly</h3>
                </div>
    </header>
    <div >
            {% block content %}
            {% endblock %}
    </div>

    <footer >
        <div class="container">
            <p>&copy; {% now 'Y' %} LIN et MERLIER</p>
        </div>
    </footer>


</body>

</html>

templates/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}